# Generated by Django 3.2.3 on 2021-06-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210626_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='first_name',
            field=models.CharField(default='first name', max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='last_name',
            field=models.CharField(default='last name', max_length=100),
        ),
    ]
