# Generated by Django 3.1.7 on 2021-06-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210610_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=models.ImageField(blank=True, default='default.PNG', null=True, upload_to='item_pics'),
        ),
    ]
